name: db_hooks

dependencies:
  - python=3.7.6
  - pip=20.0.2
  - appdirs=1.4.3
  - attrs=19.3.0
  - black=19.10b0
  - cachetools=3.1.1
  - cattrs=1.0.0
  - click=7.0
  - click-log=0.3.2
  - flake8=3.7.9
  - flake8-black=0.1.1
  - ipykernel=5.1.4
  - keyring=21.1.0
  - pandas=1.0.1
  - psycopg2=2.8.4
  - pygments=2.5.2
  - pyyaml=5.3
  - sqlalchemy=1.3.13
  - terminaltables=3.1.0
  - toml=0.10.0
  - twine=3.1.1
